function gallery(){
  $('#psd1').click(function(ev) { ev.preventDefault(); bootbox.alert('<h4 class="text-center">PSD to HTML</h4><hr><img class="img-responsive" src="img/projectpsd.png"><br/><div class="col-md-offset-3 col-md-9"><a href="https://github.com/mahendhar9/infusion" target="_blank"><button type="button" class="btn btn-success">Github URL</button></a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://mahendhar9.github.io/infusion/" target="_blank"><button type="button" class="btn btn-danger">Launch Demo</button></a></div>'); });
  $('#calci1').click(function(ev) { ev.preventDefault(); bootbox.alert('<h4 class="text-center">Calculator</h4><hr><img class="img-responsive" src="img/projectcalci.png"><br/><p class="text-center">A simple Calculator app bult using Javascript</p><div class="col-md-offset-3 col-md-9"><a href="https://github.com/mahendhar9/calci" target="_blank"><button type="button" class="btn btn-success">Github URL</button></a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://mahendhar9.github.io/calci/" target="_blank"><button type="button" class="btn btn-danger">Launch Demo</button></a></div>'); });
  $('#imgpuzzle').click(function(ev) { ev.preventDefault(); bootbox.alert('<h4 class="text-center">Image Puzzle</h4><hr><img class="img-responsive" src="img/puzzle_project.png"><br/><p class="text-center">An image puzzle game built using Javascript and JQuery.</p><div class="col-md-offset-3 col-md-9"><a href="https://github.com/mahendhar9/imagepuzzle" target="_blank"><button type="button" class="btn btn-success">Github URL</button></a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://mahendhar9.github.io/imagepuzzle/" target="_blank"><button type="button" class="btn btn-danger">Launch Demo</button></a></div>'); });
  $('#ysearch').click(function(ev) { ev.preventDefault(); bootbox.alert('<h4 class="text-center">YouSearch</h4><hr><img class="img-responsive" src="img/ysearch_project.png"><br/><hr><p class="text-center">YouSearch is a JQuery based Youtube search engine.</p><div class="col-md-offset-3 col-md-9"><a href="https://github.com/mahendhar9/ysearch" target="_blank"><button type="button" class="btn btn-success">Github URL</button></a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://mahendhar9.github.io/ysearch/" target="_blank"><button type="button" class="btn btn-danger">Launch Demo</button></a></div>'); });
  $('#mystartup').click(function(ev) { ev.preventDefault(); bootbox.alert('<h4 class="text-center">MIST Blogs</h4><hr><iframe width="560" height="315" src="https://www.youtube.com/embed/YResQaSabUk" frameborder="0" allowfullscreen></iframe><hr><p class="text-center">MIST Blogs is a social Network and microblogging platform for colleges, where each student has a personal website with a unique URL. The Student can design his/her homepage with a built-in drag & drop builder, can join communities, add friends, share files with friends and can also have a remainder of his schedule with the built-in tasks page.</p>'); });
  $('#advid').click(function(ev) { ev.preventDefault(); bootbox.alert('<h4 class="text-center">AdVid</h4><hr><img class="img-responsive" src="img/advid_project.png"><hr><p class="text-center">AdVid is a video advertising platform aimed at increasing brand-awareness among users in a unique interactive way.</p><div class="col-md-offset-3 col-md-9"><a href="https://github.com/mahendhar9/ad_vid/tree/develop" target="_blank"><button type="button" class="btn btn-success">Github URL</button></a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://mahendhar9.github.io/weather_forecast/" target="_blank"><button type="button" class="btn btn-danger">Launch Demo</button></a></div>'); });
  $('#angular').click(function(ev) { ev.preventDefault(); bootbox.alert('<h4 class="text-center">Weather Forecast</h4><hr><img class="img-responsive" src="img/weather_project.png"><hr><p class="text-center">A simple Weather forecast app built using AngularJS.</p><div class="col-md-offset-3 col-md-9"><a href="https://github.com/mahendhar9/weather_forecast" target="_blank"><button type="button" class="btn btn-success">Github URL</button></a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://mahendhar9.github.io/weather_forecast/" target="_blank"><button type="button" class="btn btn-danger">Launch Demo</button></a></div>'); });
  $('#eureka').click(function(ev) { ev.preventDefault(); bootbox.alert('<h4 class="text-center">StartupEureka</h4><hr><img class="img-responsive" src="img/startupeureka.png"><br/><hr><p class="text-center">StartupEureka is a place where you can discover how Startup founders got their Startup ideas, through a 2 min video.</p><div class="col-md-offset-4 col-md-8">&nbsp;&nbsp;&nbsp;<a href="http://startupeureka.com" target="_blank"><button type="button" class="btn btn-danger">Launch Demo</button></a></div>'); });
}

$(document).ready(gallery);